### ISSUE TITLE
没有配置任何swagger.ui下的配置时会报空指针异常

### ISSUE THREAD

**Issue by anitsirhc123** [taccisum/spring-boot-starter-swagger#1]
这样就不会了
```yaml
swagger:
  base-package: com.abc.controller
  ui:
    filter: true
```

同样的现象还出现在`swagger.info.description.show-start-date`这些配置，似乎是缺少默认值
